name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
          
      - name: Setup Node.js 22.15
        uses: actions/setup-node@v3
        with:
          node-version: '22.15'
          
      # Forzar Azure SWA a usar la versión de Node que configuramos
      - name: Create node version file
        run: |
          echo "22.15.0" > .nvmrc
          
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_KIND_MOSS_0AB3C7C0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          # Asegúrate de que la configuración de app_location, api_location y output_location sean correctas
          app_location: "/"
          api_location: ".output/server"
          output_location: ".output/public"
          # Añadir variable de entorno para forzar versión de Node
          app_build_command: "export NODE_VERSION=22.15.0 && npm run build"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_KIND_MOSS_0AB3C7C0F }}
          action: "close"
